In [ ]:
# from sklearn.neural_network import MLPClassifier
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df=pd.read_csv("food_vendor_consultation.csv")
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = Sequential()

model.add(Dense(100, activation="relu", input_shape=(X.shape[1],)))
model.add(Dense(30, activation="relu"))

model.add(Dense(3, activation="softmax"))

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)


history = model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=10,
    verbose=1
)


y_pred = model.predict(x_test)
y_pred_class = np.argmax(y_pred, axis=1)


Epoch 1/100


c:\Users\rahul kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


80/80 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3862 - loss: 4.4105
Epoch 2/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3875 - loss: 2.1776
Epoch 3/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4225 - loss: 1.7540
Epoch 4/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4663 - loss: 1.4521
Epoch 5/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4313 - loss: 1.6278
Epoch 6/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4600 - loss: 1.7870
Epoch 7/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4625 - loss: 1.6810
Epoch 8/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4462 - loss: 1.7144
Epoch 9/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4675 - loss: 1.7000
Epoch 10/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5450 - loss: 1.0641
Epoch 11/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4875 - loss: 1.2840
Epoch 12/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4787 - lo

In [ ]:
cm = confusion_matrix(y_test, y_pred_class)

print(y_pred_class)
print(cm)

[1 0 1 0 0 0 0 0 1 1 1 1 1 2 2 1 1 1 1 1 0 0 1 0 2 1 1 1 1 2 0 0 1 0 1 1 1
 1 2 2 1 1 0 0 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 1 0 1 2 2 1 1 1 0 0 1 0 0 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 2 1 2 0 0 1 1 0 1 1 1 0 1 1 0 0 1 1 2 1 0 1 0 0
 0 0 1 0 0 1 1 0 1 0 1 0 0 2 0 2 0 0 1 1 2 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 2 1 1 0 1 0 0 2 1 0 1 0 2 1 0 2 0 1 2 1 1 1 1 0 1 2 1 0 2 1 1 1 2 0 0 1
 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0]
[[45 18  1]
 [17 47  7]
 [ 5 46 14]]
