In [ ]:
import torch

In [ ]:
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name())

2.11.0+cu128
True
1
Tesla T4


In [ ]:
a=torch.empty(2,300)
print(a)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e

In [ ]:
x=torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
one_tensor=torch.ones(2,3)
print(one_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
y=torch.rand(2,3)
print(y)

tensor([[0.9628, 0.3924, 0.7095],
        [0.0243, 0.4289, 0.6935]])


In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([1,2,3,4,5,6])

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
print(torch.arange(0,10,2))

tensor([0, 2, 4, 6, 8])


In [ ]:
print(torch.linspace(0,10,10))

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
print(torch.eye(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
print(torch.eye(6,7))

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]])


In [ ]:
print(torch.full((3,3),5))

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
m=torch.tensor([[1,2,3],[4,5,6]])
print(m.shape)

torch.Size([2, 3])


In [ ]:
torch.empty_like(m)

tensor([[      562672832,       554410768, 137178044070480],
        [137178043800624, 137178043798832, 137178044086576]])

In [ ]:
torch.rand_like(m,dtype=torch.float64)

tensor([[0.6941, 0.3464, 0.9751],
        [0.7911, 0.4274, 0.4460]], dtype=torch.float64)

In [ ]:
tensor=torch.rand(2,2)
print(tensor)


tensor([[0.7909, 0.4235],
        [0.0169, 0.2209]])


In [ ]:
print(tensor+2)

tensor([[2.2426, 2.7003],
        [2.5277, 2.2472]])


In [ ]:
print(tensor-2)

tensor([[-1.2091, -1.5765],
        [-1.9831, -1.7791]])


In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)